### ISSUE TITLE
Log file names (-e/-o) truncated

### ISSUE THREAD

**Issue by tobp** [openlava/openlava#68]
A program of us calls LSF's bsub with -o and -e with the full path name to the file - that always worked fine. With OpenLava, it also works as long as the path name is short. With a deeply nested directory structure, it starts to fail as the -o and -e file names are truncated to 80 characters, creating truncated file name and the log files at odd spots.

Grepping the source code, the 80 (or 80+1 for the \0) seems to be a hard coded buffer size which is surprisingly low, given that even old file systems supported at least 255 characters while current systems pose no real limit to the path length. I think increasing the size to ~256 might be a first band aid, but the real solution would be to move to dynamically allocated memory and handle really long path names.

**Comment by openlava** [comment]
This is a bug actually. The length of the file name is supposed to be 256 indeed. This will be fixed
in the upcoming 3.1 release.

**Comment by tom-varga** [comment]
Even 256 is too small.  I've had no troubles running a CAD tool in a deep directory structure using lsf.
Unfortunately, with openlava, all kinds of havoc ensues.
No modern unix limits pathnames to 256.  It should be at least 1024
Can this be increased?

**Comment by tom-varga** [comment]
BTW, in redhat enterprise linux:

getconf PATH_MAX .
4096

getconf NAME_MAX .
255

So, it appears that openlava is confusing PATH_MAX with NAME_MAX

There should be no reason for openlava to limit the pathlength to a log file to less than 4096.

**Comment by openlava** [comment]
I think we fixed this to be PATH_MAX. Please create a patch and send us the
diffs
for us to review and check in.


Thanks
David Bigagli
www.openlava.org

**Comment by tom-varga** [comment]
Hi David,
I'm an electrical engineer working for a company that recently switched us
from lsf to openlava.
Hence, I'm only a user of openlava.
I don't have the experience to implement a patch.
So, I hope that somebody else will be able to look into the PATH_MAX issue.
Thanks,
-Tom

**Comment by openlava** [comment]
This is fixed in the latest 3.3.2 release.
