### ISSUE TITLE
Job seems finished but won't exit

### ISSUE THREAD

**Issue by leeerin6** [openlava/openlava#73]
Hi,

I'd like to report a issue that seems to happen very often in my openlava environment.
I submit with the following command:

`bsub -q queueA -m hostA -I 'hostname'`

And the result just stuck like this...
```
[userA@clientA ]$bsub -q queueA -m hostA -I 'hostname'
Job <3494> is submitted to queue <queueA>.
<<Waiting for dispatch ...>>
<<Starting on hostA>>
hostA
```
And it does not finish at all...

When I checked on hostA, I found the `ps aux` result very odd.
There will always a zombie process remaining that keeps the job's parent process from ending and reporting back to openlava.
```
root@hostA:~# ps aux | grep userA
userA 19648  0.0  0.0  12584  2848 ?        SN   12:10   0:00 /opt/openlava-3.1/sbin/res -d /opt/openlava-3.1/etc -p 46559 -m clientA /home/userA/.lsbatch/1453263042.3495
userA 19658  0.0  0.0      0     0 ?        ZN   12:10   0:00 [1453263042.3495] <defunct>
```

I'm using Openlava 3.1 on Ubuntu 14.04 environment. 
Have anyone encountered this issue and can help?
Thanks in advance.

**Comment by openlava** [comment]
What seems to happen is that res which is the parent of the jobfile does
not collect
the child for some reason and that's why the shell that runs the job is
defunct.
Try to attach gdb to res to see where it is stuck.


Thanks
David Bigagli
www.openlava.org

**Comment by leeerin6** [comment]
Hi David,

Sorry but I'm fairly new to this. Can you advice me how to attach gdb to res?

Thank you very much for your help!!!

**Comment by openlava** [comment]
Hi,
at the command line:

>gdb /full/path/to/res pid

at the gdb prompt

(gdb) where
(gdb) quit

Did you build openlava by yourself?



Thanks
David Bigagli
www.openlava.org

**Comment by leeerin6** [comment]
Hi,

I didn't build openlava on my own. I'm using the debian package downloaded from Openlava website.

I've attached gdb to a hanging process and here's the output:

```
Attaching to process 3967
Reading symbols from /opt/openlava-3.1/sbin/res...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libpthread-2.19.so...done.
done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Loaded symbols for /lib/x86_64-linux-gnu/libpthread.so.0
Reading symbols from /lib/x86_64-linux-gnu/libnsl.so.1...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libnsl-2.19.so...done.
done.
Loaded symbols for /lib/x86_64-linux-gnu/libnsl.so.1
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libc-2.19.so...done.
done.
Loaded symbols for /lib/x86_64-linux-gnu/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.19.so...done.
done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Reading symbols from /lib/x86_64-linux-gnu/libnss_files.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libnss_files-2.19.so...done.
done.
Loaded symbols for /lib/x86_64-linux-gnu/libnss_files.so.2
Reading symbols from /lib/x86_64-linux-gnu/libnss_nis.so.2...Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/libnss_nis-2.19.so...done.
done.
Loaded symbols for /lib/x86_64-linux-gnu/libnss_nis.so.2
__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135	../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
```

It seems like stucking in finding a file that does not exist. 
I've checked 3 other hanging processes and the results are the same.
Do you have any idea if I'm missing some library in my Ubuntu?

Thank you.

**Comment by openlava** [comment]
But where is the stack. At the gdb prompt type: where
Like this:

debugme->where
#0  0x00007f27fcf79393 in __select_nocancel () from /lib64/libc.so.6
#1  0x000000000040c22c in main (argc=2, argv=0x7ffc1465dbf8) at res.c:384



Thanks
David Bigagli
www.openlava.org

**Comment by leeerin6** [comment]
Hi,

Sorry I have updated the stack in the previous post.

```
(gdb) where
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00002b69e4376657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00002b69e4376480 in __GI___pthread_mutex_lock (mutex=0x66a0c0) at ../nptl/pthread_mutex_lock.c:79
#3  0x00000000004247f2 in ls_syslog ()
#4  <signal handler called>
#5  0x00002b69e488f245 in __GI___lxstat (vers=<optimized out>, name=0x66a100 "/opt/openlava-3.1/log/res.log.hostA", buf=0x7ffe3b567f20)
    at ../sysdeps/unix/sysv/linux/wordsize-64/lxstat.c:35
#6  0x0000000000424966 in ls_syslog ()
#7  0x000000000040bc16 in main ()
```

**Comment by openlava** [comment]
The res is deadlocked in a signal handler, this has been fixed while ago,
precisely in
the commit ac7f4b6980e9973ad.

My suggestion is to get the latest 3.1.2 version:

http://www.openlava.org/download/download.html

I would also suggest you build it by yourself so you know exactly what are
you running,
also binaries are not always portable across linux distros.






Thanks
David Bigagli
www.openlava.org

**Comment by leeerin6** [comment]
Hi David,

I've updated the binaries with the self-compiled 3.1.2 version.
The issue seems resolved. Thank you very much for such a prompt support!!! : )

**Comment by sgivan** [comment]
Thanks for the little debugging lesson!
 Scott Givan
@sgivan

**Comment by openlava** [comment]
You are welcome! :-))


Thanks
David Bigagli
www.openlava.org
