### ISSUE TITLE
segfault in lim

### ISSUE THREAD

**Issue by CraigNoble** [openlava/openlava#76]
segfault at 10 ip 0000000000422e3e sp 00007ffd65b1dee0 error 4 in lim

Using addr2line: openlava/lsf/lim/lim.load.c:265

Built using git commit 296f8306bb762f5f42e5c4cbde076fec0580455f (Fix bug in lsb.hosts causing mbatchd core dump.) on CentOS 6.

Please let me know if there is anything I can do to help.

**Comment by openlava** [comment]
Do you have the core file? We could look at the stack and examine the
variable.
Does it core dump always or just one time event?


Thanks
David Bigagli
www.openlava.org

**Comment by CraigNoble** [comment]
It only happens on one node, seems to be quite predictable now after 20 mins or so although it was stable for weeks (I updated to latest after noticing "Various memory fixes" in the commit log).

No core dump this time, I'll install abrt and try to catch one later on today (it's a diskless node, so minimal installation).

**Comment by openlava** [comment]
This is the master branch right?


Thanks
David Bigagli
www.openlava.org

**Comment by CraigNoble** [comment]
Currently it's master but until this morning I was running release 3.1.2 so it exists on both.

**Comment by openlava** [comment]
Any thing funny with name resolution? The line 265 is a memcpy() of the
address of
the master host. If you can reproduce you could run that slave lim under
valgrind:

valgrind --log-file=Log ./lim -2

and wait to see if valgrind reports any memory errors.



Thanks
David Bigagli
www.openlava.org

**Comment by CraigNoble** [comment]
Name resolution is done via /etc/hosts. Nothing funny I can think of in there.

I’ll run valgrind and see what it says.

**Comment by CraigNoble** [comment]
Valgrind log and end of the console output attached, still no coredump, not sure why it's not producing one, it really should be.

[output.log.txt](https://github.com/openlava/openlava/files/112492/output.log.txt)
[valgrind.lim.log.txt](https://github.com/openlava/openlava/files/112486/valgrind.lim.log.txt)

**Comment by openlava** [comment]
Two suggestions to try.

1) Rebuild on the very same OS the lim is running
2) Switch back to 3.1.2 on this host the protocol between lims and commands
did not change so the versions are compatible.


Thanks
David Bigagli
www.openlava.org
