### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sspwin** [openlava/openlava#77]
Support for LSB_SUB_COMMAND_LINE in esub, this helps to filter what command the user has submitted and process it in esub. I am now using version 3.1.3

**Comment by openlava** [comment]
This is supported in OpenLava already.

**Comment by sspwin** [comment]
I dont see it working.
below is my esub

#!/bin/sh
#esub always redirect stdout to stderr
exec 1>&2
. $LSB_SUB_PARM_FILE
echo "this is esub"
echo "$LSB_SUB_QUEUE"
echo "$LSB_SUB_COMMAND_LINE"
exit 0
________________________________________________________________

and this is what i get when i submit the job.

 bsub -q lnx64 sleep 10
this is esub
lnx64

Job <14607> is submitted to queue <lnx64>.

LSB_SUB_COMMAND_LINE does not hold sleep 10, why is that?

**Comment by sspwin** [comment]
Also the man page for openlava esub does not have this variable. please refer this link.
https://github.com/openlava/openlava/blob/master/lsf/man/man8/esub.8

**Comment by openlava** [comment]
Did you configure it in your lsf.conf?


Thanks
David Bigagli
www.openlava.org

**Comment by sspwin** [comment]
LSB_SUB_COMMAND_LINE is supported and works in OpenLava. Just like
in LSF users have to enable it using LSB_SUB_COMMANDNAME=y parameter
in lsf.conf

got your mail, added it to lsf.conf and its working. Thank you.
