### ISSUE TITLE
segfault in lim

### ISSUE THREAD

**Issue by ah19** [openlava/openlava#78]
Valgrind output attached. 

openlava 2.2 works fine, 3.1.2, 3.2.0 and 3.1.3 all give me segfaults (seen in /var/log/syslog)

Ubuntu 14.04 64bit

[valgrind_output.txt](https://github.com/openlava/openlava/files/151394/valgrind_output.txt)

**Comment by openlava** [comment]
Thanks for the valgring output it seems that the run queue length values
r15s, r1m and r15m are somehow wrong. If you have the core file could
you please print those values from the stack?

Can you also append the output of this command: $ cat /proc/loadavg
I would expect an output like this:

$ cat /proc/loadavg
0.02 0.01 0.00 1/664 29043




Thanks
David Bigagli
www.openlava.org

**Comment by openlava** [comment]
By the way Ubuntu 15.10

$ uname -a
Linux ubuntu 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016
x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:    wily

works just fine:

Mar  1 10:40:41.357044 2008 7 33 queuelength: Got run queue length r15s
0.27 r1m 0.22 r15m 0.11






Thanks
David Bigagli
www.openlava.org

**Comment by ah19** [comment]
The strangest thing is that I installed it earlier from the same base ubuntu image and it worked fine, then I set up this cluster and none of the identical machines work.

```
vagrant@head:~/openlava-3.1.2$ cat /proc/loadavg
0.01 0.02 0.05 1/133 15578
```

The output from lim is very odd:
```
vagrant@head:~/openlava-3.1.2$ sudo -u openlava /opt/openlava-3.1/sbin/lim -2
Reading configuration from /opt/openlava-3.1/etc/lsf.conf
main: Real uid is 1000, not root
main: Effective uid is 1000, not root
Mar  1 09:41:34.504876 15576 5 6821344 I��L�L$0L�D$(H�|$ H�t$H�T$H�LH�$H��HA��ffffff.�
Mar  1 09:41:34.504970 15576 7 6821344 �+�
Mar  1 09:41:34.505545 15576 7 6821344
Mar  1 09:41:34.505643 15576 7 6821344
Mar  1 09:41:34.506033 15576 3 6821344 %s belongs to cluster %s
Mar  1 09:41:34.506105 15576 3 6821344

Mar  1 09:41:34.506181 15576 3 6821344

Mar  1 09:41:34.506244 15576 3 6821344

Mar  1 09:41:34.507276 15576 7 6821344 �;y
Mar  1 09:41:34.507457 15576
```

my lsf.conf:
```
LSF_SERVERDIR=/opt/openlava-3.1/sbin
LSF_BINDIR=/opt/openlava-3.1/bin
LSB_SHAREDIR=/opt/openlava-3.1/work
LSF_ENVDIR=/opt/openlava-3.1/etc
LSF_LIBDIR=/opt/openlava-3.1/lib

LSF_CONFDIR=/opt/openlava-3.1/etc
LSB_CONFDIR=/opt/openlava-3.1/etc

LSF_LOGDIR=/opt/openlava-3.1/log
LSF_LOG_MASK=LOG_WARNING

LSF_LIM_PORT=6322
LSF_RES_PORT=6323
LSB_MBD_PORT=6324
```

I don't know if I have the core file or not. How do I print the values from the stack in the core file?

**Comment by openlava** [comment]
/proc/loadavg is fine. The output from lim does not make sense indeed. Did
you build this distribution by yourself?
You always want to build on the very same platform on which you run
otherwise strange things will happen.
In my experience binaries and libraries are not portable across distros.

If you have the core, it should be in tmp, file do this:

$ gdb /full/path/to/lim /tmp/core.xxx
$ (gdb) where <- this prints the stack
Then in your case you have to go to frame 3 I think
(gdb) frame 3
(gdb)print *r15s, *r1m, *r15m

by looking at the output from lim there is a problem with this build.




Thanks
David Bigagli
www.openlava.org

**Comment by ah19** [comment]
I do not appear to have gotten a core dump, I could only find one for res and it was from an older version so I will leave it for now.

I have a script that builds the distribution so it was definitely built on that machine, but I just got a fresh checkout which works perfectly after building it manually.

I forgot that in my build script I insert the OPENLAVA_VERSION into lsf.h because without it drmaa would not build against it. I originally wrote it for 2.2, and a third version number screwed my script up so my lsf.h looked like this:

```
#define OPENLAVA_XDR_VERSION 31

#define OPENLAVA_VERSION    31.2
#define LSF_DEFAULT_SOCKS       15
```

I will change the drmaa wrapper to look in config.h instead of hacking on lsf.h

Could having that incorrect OPENLAVA_VERSION explain my weird build?

Either way I will close this issue as it's now working

**Comment by openlava** [comment]
Changing the OPENLAVA_VERSION should not cause this, that's a protocol
version and it is used for backward compatibility. If for whatever reason
you need to change this number you probably want to do it in configure.ac
and then boostrap the project.  However I would not recommend to change the
released version, there has to be
another way to accomplish what are you trying to do.

Good that it works now!


Thanks
David Bigagli
www.openlava.org
