### ISSUE TITLE
intermittent libgcc must be installed error

### ISSUE THREAD

**Issue by ah19** [openlava/openlava#82]
I am currently doing some stress testing of my openlava cluster, submitting a few thousand 'sleep 60' jobs. One job in every thousand or so will die with the following error in the stderr:

```
libgcc_s.so.1 must be installed for pthread_cancel to work
```

Do you have any idea why this might happen with a simple sleep? I have gcc installed on all the nodes:

```
vagrant@head:~$ locate libgcc
/lib/x86_64-linux-gnu/libgcc_s.so.1
/usr/lib/vmware-tools/lib32/libgcc_s.so.1/libgcc_s.so.1
...
```

```
vagrant@head:~$ file /lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libgcc_s.so.1: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=36311b4457710ae5578c4bf00791ded7359dbb92, stripped
```

I have no idea how I can debug this really as I'm not sure where the error is even being generated

**Comment by openlava** [comment]
I cannot help directly but somebody on the list solved this issue. I
suggest you write
to the openlava-users rather than github.


Thanks
David Bigagli
www.openlava.org

**Comment by ah19** [comment]
reposted on openlava-users: https://groups.google.com/forum/#!topic/openlava-users/ZPbMfua7YL8
