### ISSUE TITLE
3.3 tarball/tag?

### ISSUE THREAD

**Issue by dougalb** [openlava/openlava#83]
Any plans to tag/release a 3.3 tarball?

**Comment by openlava** [comment]
The 3.3 branch was released March 3.1 commit
a63e5bee8f8a7134eafe2d19fbb80e7667569c1c


Thanks
David Bigagli
www.openlava.org


On Fri, Apr 29, 2016 at 1:54 AM, Dougal Ballantyne <notifications@github.com

**Comment by dougalb** [comment]
Yeah, I was just asking when you plan to tag it, so it's easier to download as a tarball?

https://github.com/openlava/openlava/tags

**Comment by openlava** [comment]
We did not tag because there is a branch and you can check out that specific
commit related to 3.3.0 release. Why do you think tagging is better?
I was thinking to only tag dot releases, but we can change it.


Thanks
David Bigagli
www.openlava.org

**Comment by dougalb** [comment]
Tagging automatically enables a .tgz/.zip download URL.

**Comment by openlava** [comment]
I have tag 3.3.1 release.


Thanks
David Bigagli
www.openlava.org
