### ISSUE TITLE
CPU affinity resource type support

### ISSUE THREAD

**Issue by leeerin6** [openlava/openlava#85]
Hi,

Is CPU affinity resource type supported in OpenLava 3.1.2?
We're trying to restrict the resource allocation of each job submitted in to Openlava, i.e. each job can allocate maximum of 12 cores.

I was using LSF and the requirement can be done through the following bsub command.

`bsub -q restrictq -I -R "select affinity[thread(4)]" command`

Can this be done by any available way in OpenLava?
Great thanks for any help.

**Comment by openlava** [comment]
This should be available in the latest 3.3.2.
